name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validasi HTML
        run: |
          npm install -g htmlhint
          htmlhint index.html

      - name: Deploy ke GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
