name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validasi HTML
        run: |
          npm install -g htmlhint
          htmlhint index.html

      - name: Login ke Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/web-paris-cafe:latest .

      - name: Push ke Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/web-paris-cafe:latest

      - name: Deploy ke GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
